# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/ufo22940268

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: https://twitter.com/hongbosb
google_plus: https://plus.google.com/114653038771687386034
fb_admins:
fb_app_id: https://www.facebook.com/profile.php?id=100005478555637
